name: Publish Python Package

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Build package with uv
        run: uv build

      - name: Publish package with uv
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
